### ISSUE TITLE
Typo for Blitz

### ISSUE THREAD

**Issue by AbsToFlab** [billy-yoyo/RainbowSixSiege-Python-API#11]
No idea if this is the proper place to post this but doing a stat check of Blitz has a typo. instead of "Enemies Flashed" it says "Enemies Flahsed"

**Comment by billy-yoyo** [comment]
People have told me about this so many times, and I keep forgetting to fix it, at this point it might as well count as an easter egg.

I joke, I'll do a quick update in a sec, not going to bother updating the PyPI package until I've updated for the new season though :)

**Comment by billy-yoyo** [comment]
Fixed, will be released as part of 0.7

**Comment by billy-yoyo** [comment]
Released with 0.7.0
