### ISSUE TITLE
Not connecting (Unclosed client session)

### ISSUE THREAD

**Issue by xxmattnappo** [billy-yoyo/RainbowSixSiege-Python-API#13]
I just installed your api and copied the example starter code into a new python file. The only thing I changed was my email and password, and the ingame username to look up. I saw the earlier issue [here](https://github.com/billy-yoyo/RainbowSixSiege-Python-API/issues/9) and tried the fixes you said, didn't work. The error I am getting when running the example script is:

`78`
`Unclosed client session`
`client_session: <aiohttp.client.ClientSession object at 0x102dabda0>`

Why is this happening and how can I fix it?

EDIT: I am using python version 3.5.4.

**Comment by billy-yoyo** [comment]
That's just a warning. I might do something to get rid of it soon, but it's nothing to worry about, it doesn't do anything from working

**Comment by xxmattnappo** [comment]
Oh okay, Thank.
