### ISSUE TITLE
Update to Grim Sky (add Maverick & Clash)

### ISSUE THREAD

**Issue by billy-yoyo** [billy-yoyo/RainbowSixSiege-Python-API#14]
NOTE: This issue is for when the new season gets released, for now this work doesn't need to be done since the changes are still in TTS.

I'm away for all of September, so won't be able to update the API to the latest season until October.
If anyone wants to do it themselves whilst I'm away, the following needs to be updated:

- The url "https://ubistatic-a.akamaihd.net/0058/prod/assets/data/operators.3a2655c8.json" in get_operator_definitions. The number (3a2655c8) will need to be updated with whatever the latest version of this is. This can be found by logging in to the official rainbow statistics website and checking your network log for this file.

- Two entries will need to be added to the OperatorStatisticNames dictionary (e.g. "CLASH": "enemies tazed"). It's not always clear what these statistic names are, you can just guess for now then fix it later if it's obviously wrong.

If anyone makes a PR with these changes, I have some access to internet during September so I should be able to merge it, otherwise I'll just do it when I get back. 

Either way, pypi package won't be updated until I get back.

**Comment by zMCdarc** [comment]
i think it has changed domain to `game-rainbow6.ubi.com`?
i got the new operators url from 

`https://game-rainbow6.ubi.com/assets/data/operators.682af7ce0969c4ec.json`

,,, if u didnot get back this weekend, i will do it myself and create the PR.

and , why i got  FailedToConnect error by using the example code... i can get the right response when i do the request by myself.

@billy-yoyo

**Comment by zMCdarc** [comment]
i guess i am right? the cdn returned 404 status code.
`https://ubistatic-a.akamaihd.net/0058/prod/assets/data/operators.682af7ce0969c4ec.json`

**Comment by zMCdarc** [comment]
all right, the account unowned rainbow6 cannot be used to do the query.

**Comment by billy-yoyo** [comment]
Changes added by @zMCdarc

**Comment by hayo-k** [comment]
I seem to get a  HTTPException: BAD REQUEST (status code: 400) when using the new link (https://game-rainbow6.ubi.com/assets/data/operators.682af7ce0969c4ec.json) 
I tried it with 2 different accounts (one that owns r6 on pc and one I created for my programm)

**Comment by billy-yoyo** [comment]
couldn't reproduce @hayo-k's error, released these changes in 0.8.0
