### ISSUE TITLE
Maintaining a logged in status

### ISSUE THREAD

**Issue by tprocter1984** [billy-yoyo/RainbowSixSiege-Python-API#17]
Is there a way that I could maintain a logged in status, maybe through an access token or something similar to prevent the api from blocking multiple calls?

I'm trying to run some tests on a script and I get blocked after a short period, presumably from logging in too many times. 

Thanks in advance, 

Tom

**Comment by billy-yoyo** [comment]
Use a single Auth object, don't keep recreating them.
