### ISSUE TITLE
load_all_operators()

### ISSUE THREAD

**Issue by CRSLEE** [billy-yoyo/RainbowSixSiege-Python-API#19]
Hello,
im using your API for about half a year now.
Today i wanted to update to 0.8 to get the new operator stats (Clash and Mav).
I noticed that i didin't got any data for those two.

Could you please have a look at method => load_all_operators()
There is a for-loop => for operator in OperatorStatistics:
I don't see the two operators in OperatorStatistics list but i do see them in OperatorStatisticNames list.
So i changed the for-loop and now i got all data.

Could you please check if there is a fault in the script or maybe a fault on my understanding?!

Best regards
CRSLEE

**Comment by billy-yoyo** [comment]
You're completely right, I completely missed that when I changed to using the operator definitions instead. I'll update this ASAP to get it working - sorry :)

**Comment by CRSLEE** [comment]
Ok, perfekt! 
Thank you for your help! :) 

Best regards
CRSLEE

**Comment by billy-yoyo** [comment]
Fixed, will comment again when this is released to PyPI
