### ISSUE TITLE
Failed to connect to the rainbow six api

### ISSUE THREAD

**Issue by Dennisbonke** [billy-yoyo/RainbowSixSiege-Python-API#21]
There is a red discord bot cog which uses your api, with success for quite some time now.
However, since the 3rd of november 2018, we get errors when we issue a request. It seems like public-ubiservices.ubi.com is dead, and the links should be updated accordingly. I can't do this as I have no idea where the new api is, or maybe it is a temporary issue, but it is strange that is is consistently happening for over a month now. isitdownrightnow reports that it is down for them as well and in my browser I can't connect as well. Is there anything we or you can do about this?

**Comment by Dennisbonke** [comment]
I live in the Netherlands, using a server hosted in Amsterdam. It has always worked from that server until the 3rd of November. I will try a other server that I have and I’ll report back

**Comment by billy-yoyo** [comment]
I'm away for the holidays so I can't look in to it until January, sorry

**Comment by Dennisbonke** [comment]
@zMCdarc tried it on a different server but I got the same error

```python
Exception in command 'r6s rank'
Traceback (most recent call last):
  File "lib/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/PotatoBot/Red-DiscordBot/cogs/rainbow6siege.py", line 225, in _rank
    p = await self.get_player(player, platform)
  File "/home/PotatoBot/Red-DiscordBot/cogs/rainbow6siege.py", line 59, in get_player
    ).get_player(player, plat)
  File "/usr/local/lib/python3.6/site-packages/r6sapi/r6sapi.py", line 531, in get_player
    results = yield from self.get_players(name=name, platform=platform, uid=uid)
  File "/usr/local/lib/python3.6/site-packages/r6sapi/r6sapi.py", line 497, in get_players
    data = yield from self.get("https://public-ubiservices.ubi.com/v2/profiles?nameOnPlatform=%s&platformType=%s" % (parse.quote(name), parse.quote(platform)))
  File "/usr/local/lib/python3.6/site-packages/r6sapi/r6sapi.py", line 403, in get
    raise FailedToConnect
r6sapi.r6sapi.FailedToConnect

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "lib/discord/ext/commands/bot.py", line 846, in process_commands
    yield from command.invoke(ctx)
  File "lib/discord/ext/commands/core.py", line 634, in invoke
    yield from ctx.invoked_subcommand.invoke(ctx)
  File "lib/discord/ext/commands/core.py", line 374, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "lib/discord/ext/commands/core.py", line 54, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: FailedToConnect:
```

**Comment by billy-yoyo** [comment]
Is this possibly a credentials issue? I get a similar looking error if I try to log in with an invalid email/password.

I'll raise a separate ticket to make the error more clear (if it's possible), so it's obvious when it's a credentials issue.

**Comment by billy-yoyo** [comment]
created this ticket to solve this issue: https://github.com/billy-yoyo/RainbowSixSiege-Python-API/issues/28

**Comment by Dennisbonke** [comment]
While it is not a credentials issue (seeing as those have not changed), this issue can remain closed as it started working again as of today
