### ISSUE TITLE
"get_operator_badge" doesnt return complete url but only "/assets/..."

### ISSUE THREAD

**Issue by TECHNOFAB11** [billy-yoyo/RainbowSixSiege-Python-API#23]
What is the complete URL? I only need the Server, then i can add it before every url "get_operator_badge" returns

**Comment by anakincho** [comment]
`"https://game-rainbow6.ubi.com"` would be the URL. Here is an example: https://game-rainbow6.ubi.com/assets/images/small-nomad.50642fb12f.png

Hope this helps! @TECHNOFAB11

**Comment by billy-yoyo** [comment]
The code should be adding this automatically, the related snippet is:
```
if not badge.startswith("http"):
            badge = "https://game-rainbow6.ubi.com/" + badge
```
It works this way for me.
