### ISSUE TITLE
New operator link. But with error's

### ISSUE THREAD

**Issue by hayo-k** [billy-yoyo/RainbowSixSiege-Python-API#26]
The new operator link in get_operator_defenitions() appears to be https://game-rainbow6.ubi.com/assets/data/operators.24b865895.json The only problem is ubi forgot to add the UniqueStatistic for Nomad and Kaid (they are there for Mozzie and Gridlock tho). 
So unfortunatly the API throws an keyerror in get_operator_statistic() on the return.

My current workaround (not the most beautifull coding)
after these lines of code in get_operator_definitions():
`resp = yield from self.session.get("https://game-rainbow6.ubi.com/assets/data/operators.bbbf29a090.json")`
`data = yield from resp.json()`

I added:
`resp_y4 = yield from self.session.get("https://game-rainbow6.ubi.com/assets/data/operators.24b865895.json")`
`data_y4 = yield from resp_y4.json()`
`data["mozzie"] = data_y4["mozzie"]`
`data["gridlock"] = data_y4["gridlock"]`

and in OperatorStatisticNames{} I added"
`"MOZZIE": "Drones Hacked",    "GRIDLOCK": "Trax Deployed"`

**Comment by billy-yoyo** [comment]
Thanks for pointing this out - probably would have annoyed me otherwise. I've put in a more "baked" solution in to the api which just accounts for operators with missing unique statistics.
