### ISSUE TITLE
Documentation broken?

### ISSUE THREAD

**Issue by TECHNOFAB11** [billy-yoyo/RainbowSixSiege-Python-API#29]
For me, the readthedocs.com documentation is only showing headlines but nothing beneath. Looking into the rst file, it seems like the text is missing there too?

**Comment by amaothree** [comment]
Need the document work or just a simple API list.
Thanks developer.

**Comment by billy-yoyo** [comment]
I will fix this asap, hopefully today if I remember after work

**Comment by akinmetin** [comment]
As you say, detailed documentation need asap. Have you covered all ubisoft API calls?

**Comment by billy-yoyo** [comment]
Sorry, been very busy this week, haven't had any time at all. Got a free weekend so I'll get the docs fixed. 

@akimmetin, I can't be certain I have all of the API calls but I believe it has pretty much all be the player data related endpoints. If it doesn't it should be easy to add them.

**Comment by billy-yoyo** [comment]
Fixed.
