### ISSUE TITLE
GT "found" in DM, but not in Channel

### ISSUE THREAD

**Issue by robertjacobson** [billy-yoyo/RainbowSixSiege-Python-API#3]
There appears to be a case where r6 bot fails to find a user when messaged via channel, but via direct message the query is successful. 

E.g.: `Bodybag.Bees` (uplay or xbox).

**Comment by billy-yoyo** [comment]
I can't reproduce - I think uplay went down for a tiny bit yesterday so it might have just been coincidental timing
