### ISSUE TITLE
Update to Operation Ember Rise

### ISSUE THREAD

**Issue by billy-yoyo** [billy-yoyo/RainbowSixSiege-Python-API#31]
See https://github.com/billy-yoyo/RainbowSixSiege-Python-API/issues/14 for details about how to get the new ops working.

There'll also be some changes required to the rank levels (images & names), these can be found in https://github.com/billy-yoyo/RainbowSixSiege-Python-API/blob/master/r6sapi/ranks.py

**Comment by connorbeshears** [comment]
I've got a fix for this waiting, I can throw it in a new branch if I'm invited to the project

**Comment by billy-yoyo** [comment]
done with version 1.1
