### ISSUE TITLE
Investigate way of automatically getting latest operator definitions.

### ISSUE THREAD

**Issue by billy-yoyo** [billy-yoyo/RainbowSixSiege-Python-API#33]
I've looked in to this in the past, but couldn't find anything at the time. I think it's worth having another shot at it, since it would prevent the package having to be updated for every operation.

**Comment by Danampasis** [comment]
Hello, maybe scrapping their new website could work for updating the operators automatically each season. There's a page which it has all the operators listed, https://rainbow6.ubisoft.com/siege/en-gb/game-info/operators.aspx .

**Comment by Eloncase** [comment]
Hi!
The only way I've found is to parse HTML and two JS files like [this](https://github.com/Eloncase/RainbowSixSiege-CSharp-API/blob/17f1918884bf7f38917efdee8b3c369f20342257/R6SiegeAPI/API.cs#L111). Not sure if this is a good idea but it works

Basically what the function does is:
- downloads html from `https://game-rainbow6.ubi.com/`
- parses it for two js files (`assets/scripts/main.<hash>.js` and `assets/scripts/vendor.<hash>.js`)
- downloads those two
- parses the main js file for `assets/data/operators.<hash>.json`, `assets/data/weapons.<hash>.json` and `assets/data/seasons.<hash>.json`
- parses the vendor js file for `assets/locales/locale.<lang_tag>.<hash>.json`

**Comment by billy-yoyo** [comment]
Yeah I think that's the only realistic way of doing it - problem is we'd need people to do this web scraping every time people start the library, unless we implement some permanent cashing which I'm hesitant to do.

I think unless I can find a solution which only requires a single request, and a small amount computation, I'm going to keep it how it is right now.

A possible alternative is I host a file somewhere which has the hashes, the library downloads that file, and I can update it automatically using this kind of method.

**Comment by Eloncase** [comment]
I've made a [server](https://github.com/Eloncase/r6unhasher) for that purpose, currently hosting it [here](https://r6unhash.tk/). Feel free to use it. Haven't really tested it much tho. I guess you could still implement a web scraping as a fallback option.

**Comment by billy-yoyo** [comment]
Wow, thanks a bunch! I'll implement it on the API asap (over this weekend). Yeah, I'll fall back on either web scraping or a hard coded hash, might do both and let the user decide which one to use.

**Comment by billy-yoyo** [comment]
Added to last commit (1728a8f), will be in the next version. Thanks again @Eloncase.
