### ISSUE TITLE
Map Site Stats?

### ISSUE THREAD

**Issue by parkerlink** [billy-yoyo/RainbowSixSiege-Python-API#35]
I'm new to the whole siege api thing so I'm not sure what the limitations are but is there anyway to collect Map stats? Like how often a site is selected in ranked/unranked. For example we all know on a map like bank where Open Area is the least favorable site compared to Basement, I was wondering if there was a way to get a number for it to express a percentage. I don't know if ubisoft has a number or not it would just be cool to know, thanks!

**Comment by billy-yoyo** [comment]
I've tried looking for these kinds of stats before on their API but couldn't find anything, I don't think the data they keep is that granular unfortunately.

**Comment by parkerlink** [comment]
i thought it was worth asking thanks a bunch man, I'm really interested in this api stuff you posted, it's been great and really simple to use
