### ISSUE TITLE
Too many calls per profile

### ISSUE THREAD

**Issue by test2g** [billy-yoyo/RainbowSixSiege-Python-API#36]
如题，查的次数一多就这样了，有什么好的规避方法吗？

**Comment by billy-yoyo** [comment]
You can use the player batch API to make requests for multiple players at once. There's an example of how in the examples folder. 

Sorry I can't speak Chinese - hope you can understand anyway :)

**Comment by test2g** [comment]
Thx for your advice.
Sry I didn't notice the batch API, I'll try to use this to figure problem out.
