### ISSUE TITLE
Bot won't pull stats

### ISSUE THREAD

**Issue by ShellRazor44** [billy-yoyo/RainbowSixSiege-Python-API#37]
When I attempt to get stats in my server the bot no longer will pull them. It only returns a message "Couldn't find any users matching ..." 
![r6bot](https://user-images.githubusercontent.com/57027194/69001060-1c3f8000-089e-11ea-9f2d-13947fe5f7a4.PNG)

**Comment by zazzik** [comment]
same thing, "r6s stats" is not working

**Comment by billy-yoyo** [comment]
This is an issue with the bot, not the library, so I'm closing this issue. I'll fix the bot though.
