### ISSUE TITLE
How to gain access to ubi services?

### ISSUE THREAD

**Issue by Gibbo3771** [billy-yoyo/RainbowSixSiege-Python-API#39]
Hi, I can't find anywhere else to ask this so hopefully you can help.

I am currently writing an app that needs access to the ubi api. I noticed you are hitting this endpoint for the authentication:

`https://connect.ubi.com/ubiservices/v2/profiles/sessions`.

I also see a bunch of other end points prefixed with `public`, such as `FETCH_STATISTIC = "https://public-ubiservices.ubi.com/v1/spaces/%s/sandboxes/%s/playerstats2/statistics?populations=%s&statistics=%s"`.

I am writing the app in in Node, so will need to make a small wrapper to handle all of this.

Any advice?

**Comment by billy-yoyo** [comment]
I wrote a short bit the documentation about how the authentication works

https://rainbowsixsiege-python-api.readthedocs.io/en/latest/how.html#generating-the-token

For the requests, that fetch_statistic variable is the generic URL format for statistic requests, I'm not a home right now but can explain that bit later. Hopefully this helps, feel free to send me more questions :)

**Comment by billy-yoyo** [comment]
no further comment from poster for over a month, so closing
