### ISSUE TITLE
Needs to be updated for Year 2 Season 3 Operators

### ISSUE THREAD

**Issue by tmercswims** [billy-yoyo/RainbowSixSiege-Python-API#4]
I'm missing my Ying Lesion and Ela 😢😜

**Comment by billy-yoyo** [comment]
Done :)

**Comment by tmercswims** [comment]
Awesome, thanks! :D

**Comment by tmercswims** [comment]
I don't want to be a bother, but would it be possible to push the new version to PyPI?
