### ISSUE TITLE
Authentication Deprecated.

### ISSUE THREAD

**Issue by xMistt** [billy-yoyo/RainbowSixSiege-Python-API#42]
When calling `https://connect.ubi.com/ubiservices/v2/profiles/sessions`, I seem to always get 404. I think Ubisoft has deprecated this endpoint and is now using another one.

**Comment by Ullizzzz** [comment]
change https://connect.ubi.com/ubiservices/v2/profiles/sessions to https://public-ubiservices.ubi.com/v3/profiles/sessions

**Comment by RAYs3T** [comment]
#43

**Comment by billy-yoyo** [comment]
fixed in PR #43, will update library version soon
