### ISSUE TITLE
Http error for all requests

### ISSUE THREAD

**Issue by Danampasis** [billy-yoyo/RainbowSixSiege-Python-API#47]
r6sapi.exceptions.InvalidRequest: HTTP 403: The Service: RendezVous, is not currently available for Application 39baebad-39e5-4552-8c25-2c9b919064e2 on the Gateway.

**Comment by hayo-k** [comment]
Ubisofts api seems to be offline since yesterday

**Comment by Danampasis** [comment]
Yeah just noticed, even on their website https://game-rainbow6.ubi.com/en-us/uplay/player-statistics/{uplay_id}/multiplayer everything returns a 403 error. Closing the issue.
