### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by DestinyofYeet** [billy-yoyo/RainbowSixSiege-Python-API#49]
Your example code in the Github Repository is different then in your documentation.

Github: https://i.imgur.com/jARDfiK.png

Documentation: https://i.imgur.com/wbKXvYR.png

**Comment by billy-yoyo** [comment]
I'll update the documentation to match at some point - they're technically the same thing, the github version just uses 3.5+ asyncio syntax whereas the documentation version is the old 3.4 asyncio syntax.

**Comment by DestinyofYeet** [comment]
Ok thanks :D I got one  more question tho: Is if possible / how likely is it to get a account permanently banned?

**Comment by billy-yoyo** [comment]
I'm pretty sure it's impossible. When developing this I accidentally spammed their API several times and all I got was a temp API ban. It never effected my ability to play the game, just ability to use the API.

If you're worried about it you can just make a throwaway uplay account to use the API instead. You don't need to own rainbow six to use it.

**Comment by DestinyofYeet** [comment]
I managed to get ip temp banned from the Uplay servers cause I had like 12 throwaway accounts and I pinged the Uplay Server with all of them at once but but yeah
