### ISSUE TITLE
Ela update

### ISSUE THREAD

**Issue by caseybraith** [billy-yoyo/RainbowSixSiege-Python-API#5]
Hello,
Getting statistics for Ela doesn't seem to work, is there any chance that this script could be updated to support her?

Thanks!

**Comment by billy-yoyo** [comment]
yeah sorry I'll update ASAP, need to update the PyPI package

**Comment by billy-yoyo** [comment]
Going to update the PyPI package when the White Noise operators are working. Hopefully that should be sometime this week.

**Comment by billy-yoyo** [comment]
Updating the PyPI package now
