### ISSUE TITLE
Player object has none of the properties listed in documentation

### ISSUE THREAD

**Issue by CodingPenguin1** [billy-yoyo/RainbowSixSiege-Python-API#54]
Running `player.kills` returns an `AttributeError: 'Player' object has no attribute 'kills'`

[Documentation](https://rainbowsixsiege-python-api.readthedocs.io/en/latest/api.html#player) states that `Player` should have this property, among others

**Comment by billy-yoyo** [comment]
Are you calling player.load_general first? The player data isn't automatically populated you have to trigger the request to fetch it manually.

**Comment by CodingPenguin1** [comment]
My mistake. I forgot to `await`. Thanks for the fast response! Sugguestion to add an example using this to the docs?
