### ISSUE TITLE
Add new ops

### ISSUE THREAD

**Issue by FloatCobra** [billy-yoyo/RainbowSixSiege-Python-API#6]
Add the new ops from White Noise?

**Comment by billy-yoyo** [comment]
Will do asap, haven't been able to because the rainbow website hasn't been working for me so can't get new API names.

**Comment by billy-yoyo** [comment]
Ubi still haven't updated their API... as soon as they have I'll update the PyPI. Sorry!

**Comment by billy-yoyo** [comment]
Added, will update the pypi package asap :)
