### ISSUE TITLE
aiohttp version

### ISSUE THREAD

**Issue by Jackywathy** [billy-yoyo/RainbowSixSiege-Python-API#60]
could we get another upgrade of aiohttp version? For context I'm using this library with a discordpy chat bot, which requires aiohttp>=3.6.0,

currently this project is using aiohttp>=2.3.3,<3.0.0, so I was just wondering if there is a reason we haven't upgraded yet.

**Comment by billy-yoyo** [comment]
Yeah sure, should be an easy change

**Comment by billy-yoyo** [comment]
This change will happen under https://github.com/billy-yoyo/RainbowSixSiege-Python-API/pull/71
