### ISSUE TITLE
Add ID to get_player

### ISSUE THREAD

**Issue by FloatCobra** [billy-yoyo/RainbowSixSiege-Python-API#7]
add the ability to use the player's uplayid to get the player info

**Comment by billy-yoyo** [comment]
Shouldn't be too hard to do, I'll try add it with the white noise update stuff

**Comment by billy-yoyo** [comment]
added this functionality, you can now do:
```
auth.get_player(uid="some_unique_identifier", platform=...)
```
going to wait until I get the new operators working before I push this to PyPI
